apiVersion: v1
kind: ConfigMap
metadata:
  name: postiz-provider-edge
data:
  nginx.provider.conf: |
{{ .Files.Get "files/nginx.provider.conf" | indent 4 }}
  allowlist.txt: |
{{ .Files.Get "files/allowlist.txt" | indent 4 }}
